version: "3.4"

services:
  podcastinate:
    container_name: podcastinate
    build:
      context: ./
    working_dir: /opt/podcastinate/app
    ports:
      - 55552:433
    environment:
      - PYTHONPATH=/opt/podcastinate/app
      - API_TOKEN=${API_TOKEN}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_LISTEN=${WEBHOOK_LISTEN}
    volumes:
      - ./app:/opt/podcastinate/app
      - ./logs:/var/logs
    command: /bin/sh runfiles/run_bot.sh
